### ISSUE TITLE
Can't set a precise background color

### ISSUE THREAD

**Issue by eduardoarandah** [fabiorino/crelly-slider#10]
![ss](https://cloud.githubusercontent.com/assets/4065733/7438164/59314f48-f025-11e4-81e4-be1c35ecf5b9.png)

**Comment by fabiorino** [comment]
Hi, unfortunately for now there's no way to set a precise color. I promise that I'll add the option in the next release. There's a workaround for now: set it directly from MySql database. There's a table called "wp_crellyslider_slides". Find the "background_type_color" attribute and modify the value.
