### ISSUE TITLE
[Performance] Enqueue Javascript to footer reduce page load speed

### ISSUE THREAD

**Issue by Jonathlee** [fabiorino/crelly-slider#13]
Any chance to create an option allowing advanced user to load the javascript in footer?

common.php

```
wp_enqueue_script('jquery.crellyslider.min', CS_PLUGIN_URL . '/js/jquery.crellyslider.min.js', array(), CS_VERSION, true);
```

plus the shortcode generated Javascript to be placed in the bottom of footer

**Comment by fabiorino** [comment]
I'm sorry but for now I have no plans about that.
