### ISSUE TITLE
How about using animate.css ? 

### ISSUE THREAD

**Issue by eduardoarandah** [fabiorino/crelly-slider#17]
Have you seen this project?

It could be included very easily on crelly-slider:
https://daneden.github.io/animate.css/

Advantages:
-Easy to install and mantain via bower.json file, all you need to do is "bower install animate.css"
-More animations

All you need to do is add class="animated ANIMATION_HERE" in crelly-slider/wordpress/frontend.php

Example, swing animation:

    $output .= '<a' . "\n" .
    'class="animated swing "' . "\n" .    
    'data-top="' . $element->data_top . '"' . "\n" .
    'data-left="' . $element->data_left . '"' . "\n" .
    'data-time="' . $element->data_time . '"' . "\n" .
    'href="' . stripslashes($element->link) . '"' . "\n" .
    $target . "\n" .
    'style="' .
    'z-index: ' . $element->z_index . ';' . "\n" .
    '">' .  "\n";

**Comment by fabiorino** [comment]
Hi, yes I know animate.css but it probably won't be added because of two factors:
1) browser compatibility
2) the animation timing of animate.css is difficult to control and the css should be rewritten to fit with the current source code of the slider.
