### ISSUE TITLE
Flash of Unstyled Content

### ISSUE THREAD

**Issue by javistuff** [fabiorino/crelly-slider#2]
Hi guys!

First, let me tell you, the slider looks great. I'm truly happy there's a plugin like yours in the repo.
We are adding (a little more dedicated) support for your plugin to a theme of ours and we are noticing a flashing of the < ul > element with a shorter height version of the slides even before the loader comes in.

We've tried all sorts of display:none en several elements, seeing that the slides get shown via a a javascript display:block action, but with no success at all.

Have you seen this happening? Any clue of what could we do to avoid this flashing?

**Comment by cooperlovano** [comment]
Hello! 
I am having this same problem (the slider loads going down the whole page before it becomes styled to display as a slider) https://www.cooperlovano.design/

Is there a solution that you found that I can use? 
Thanks so much! Beautiful plugin

**Comment by fabiorino** [comment]
@cooperlovano the site you provided doesn't have Crelly Slider installed
