### ISSUE TITLE
Crelly Slider hangs at start

### ISSUE THREAD

**Issue by Maco65** [fabiorino/crelly-slider#24]
I am using Crelly Slider on my site http://po-wisle.pl/pl/home-pl/
Recently I have noticed that when I type the site address in my browser (Firefox) it shows logo, menu and blurry first slide (from slider) picture. It also show the kind of “loading” indicator (small white circle in the middle of the screen with dark blue up and down lines inside). The “loading” indicator is animated so you can think that something is going on, while nothing happens. You can wait long time (longest I have tested is 15 minutes) with no change. It is normally enough to refresh the browser (F5) and all start to work as it should.
My friend also told me that this has happened few times on his Chrome browser and I have also notices this in my iPhone.
The issue does not appear all the time – but unfortunately often enough to make a service ticket.
You may experience it by trying to type the address manually in the browser once a while.

**Comment by fabiorino** [comment]
Hi, I'm working on a fix right now. As this happens "randomly", it's harder for me to test it.
If you want, I can send you the file that should fix the problem, you'd just have to copy and paste it. Would be a be a big help for me to ensure that the fix works.

**Comment by Maco65** [comment]
Excellent,

Please send me the file and info where to place it

Maciek Szałęga


M: +48 604 495 400
F:  + 48 22 100 11 47
 
Po Wiśle Sp. z o.o, siedziba: ul. Hoża 86 lok.410, 00-682 Warszawa, NIP: 7010507098, REGON: 36250531400000, KRS: 0000575943, kapitał zakładowy: 5 000 PLN

Dnia 29.03.2016 o godz. 11:21 fabiorino <notifications@github.com> napisał(a):

**Comment by fabiorino** [comment]
I can't attach a file here. Can you provide me your mail at fabiorino@outlook.com ? Thank you

**Comment by Maco65** [comment]
I did :)

**Comment by fabiorino** [comment]
I replied. Sorry if it took so long, I was really busy this afternoon

**Comment by Maco65** [comment]
No problem.  :))

Maciek
--------------------------------------------------------------------------------
 +48 604 495 400
6+48 22 100 11 47
www.po-wisle.pl
Spółka z ograniczoną odpowiedzialnością
ul. Hoża 86 lok.410, 00-682 Warszawa
NIP: 7010507098, REGON: 36250531400000, KRS: 0000575943
kapitał zakładowy: 5 000 PLN



------ Wiadomość oryginalna ------
Od: "fabiorino" <notifications@github.com>
Do: "fabiorino/crelly-slider" <crelly-slider@noreply.github.com>
Kopia: "Maco65" <maciek.szalega@po-wisle.pl>
Wysłano: 29.03.2016 19:13:09
Temat: Re: [fabiorino/crelly-slider] Crelly Slider hangs at start (#24)

**Comment by Maco65** [comment]
Thanks. It seems that your fix is working perfectly !

**Comment by sid31dz** [comment]
Hi fabiorino i've the same problem  as marco ,  can you help me please , I sent you also a mail

**Comment by fabiorino** [comment]
Sure I'll help you. Check your emails

**Comment by slec2md** [comment]
Hi fabriono, please email me as well, same problem :(. I sent you an email as well
