### ISSUE TITLE
How to add Video ? 

### ISSUE THREAD

**Issue by techsaqib** [fabiorino/crelly-slider#25]
Hi i see the code , it has the code videos , but how to add the videos in this slider thanks , 

i am using it as a jquery plugin 

please reply as soon as possible

**Comment by fabiorino** [comment]
**For YouTube:**
<iframe frameborder="0" width="560" height="315" class="cs-vimeo-iframe " src="https://player.vimeo.com/video/17411241?api=1" data-autoplay="0" data-loop="0"></iframe>

**For Vimeo:**
<iframe frameborder="0" type="text/html" width="560" height="315" class="cs-yt-iframe " src="https://www.youtube.com/embed/Vv3lTgGn0mc?enablejsapi=1" data-autoplay="0" data-loop="0"></iframe>
