### ISSUE TITLE
getting a gap on Beaver Builder theme and page builder!

### ISSUE THREAD

**Issue by daveit** [fabiorino/crelly-slider#29]
I'm testing out crelly on a site using the beaver builder theme and it's page builder.
I'm testing a full width row and the content is set to full width.
All good except I am getting a top and bottom gap of 10 pixels.
Not sure why - the page builder row (based on bootstrap BTW) has all the padding and margins all zero'd out.
I've worked out that changing the following css fixes it, but using -ve values is not good!

.fl-node-576e0c025ee2b > .fl-module-content {
    margin-top: -10px;
    margin-bottom: -10px;
}
TIA

**Comment by daveit** [comment]
All sorted, not caused by crelly - I recreated the row and all good.
Dave

**Comment by pvschaitanya** [comment]
Hi sir
i have an issue in with crelly slider..
crelly slider is loading after the content.. so it looks odd
can you please help me on this...

where i tried with "Slider Revolution" it is loading before content
example : http://chaitanya.esy.es/revo-slider/

but "Crelly Slider" is loading after content
example : http://chaitanya.esy.es/crelly-slider/

note: the above site is in fee hosting.. so some time it is not loading.. please bare with me and please press refesh

regards
Chaitanya
