### ISSUE TITLE
Wordpress 4.8 and latest tinymce dropped wpembed which is still referenced by Crelly Slider

### ISSUE THREAD

**Issue by tpokorra** [fabiorino/crelly-slider#44]
I get this message when editing a slide:

    Failed to load plugin: wpembed from url https://www.mywordpress.com/wp-includes/js/tinymce/plugins/wpembed/plugin.min.js

I can get rid of this message by editing ./wp-content/plugins/crelly-slider/wordpress/js/admin.js and remove wpembed from the list plugins in line 916

**Comment by fabiorino** [comment]
I'm working on a fix right now
