### ISSUE TITLE
Possibility to load Slider in JS?

### ISSUE THREAD

**Issue by chakmear** [fabiorino/crelly-slider#45]
Hi,
I have my slider hidden (display none) initially and make it visible later on, but when I make it visible again, it is not loaded. I think it loads on page load and when it's hidden it doesn't get the right parameters... is there a possiblity to reload the slider afterwards, e.g. $('.slider).data(slider).reload();? I think that would fix my problem but I didn't find any function in the docs... resume() etc. doesn't work...
Thanks and greetings!
chakmear

**Comment by fabiorino** [comment]
Unfortunately that option doesn't exist. You could try to hide the slider by setting the position to absolute and top,left to -9999px or something like that

**Comment by chakmear** [comment]
Thanks for your answer and sorry for my late response :)
