### ISSUE TITLE
frontend.php - getCrellySlider($alias)

### ISSUE THREAD

**Issue by mathieu2011** [fabiorino/crelly-slider#46]
Hi there,

i was wondering: shouldn't the getCrellySlider($alias) function actually return the output? Since the $echo parameter in output() is false, the function doesn't really serve any purpose otherwise as far as i can see.

So my suggestion would be to change the function to
`function getCrellySlider($alias) {
	return CrellySliderFrontend::output($alias, false);
}`

**Comment by fabiorino** [comment]
You're definitively right! I'll fix it this afternoon
