### ISSUE TITLE
Crelly slider text show only partially in mobile view

### ISSUE THREAD

**Issue by mitdrissia** [fabiorino/crelly-slider#49]
Hi, i am using your awesome slder plugin. I only have one issue and that's is when viewing on mobile phone.
For some reason i can only see partially text block of each slider.  Could you please have a look at my site: [http://setaopleidingen.nl](http://setaopleidingen.nl) and let me know what the problem is.

thank you

**Comment by fabiorino** [comment]
Double post, let's discuss here: https://wordpress.org/support/topic/slider-text-in-mobile-not-visible/
