### ISSUE TITLE
Filter tinyMCE options

### ISSUE THREAD

**Issue by dlaxar** [fabiorino/crelly-slider#51]
Hi, 

I'd like to add a custom font to the editor. This works for the Wordpress core editors and also the "useless" editor on the crelly-slider page but it does not work on the element-editor (for slide elements). 

The underlying problem is, that the crelly-slider uses static, non-modifyable options (https://github.com/fabiorino/crelly-slider/blob/master/wordpress/js/admin.js#L899). I'd like to change that and extract these options to PHP and make them filterable (similar to https://codex.wordpress.org/TinyMCE#Customize_TinyMCE_with_Filters). I'd implement this change myself but I wanted to check in with the community if this is something you'd consider good and useful.

Looking forward to your reply, 
Daniel

**Comment by fabiorino** [comment]
It definitively is, I would really appreciate that feature!
