### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ahangarha** [fabiorino/crelly-slider#61]
Hi

I don't see `LICENSE.md` file in the repository and no license was mentioned in `README.md` file as well. What is the license of this amazing project?

**Comment by fabiorino** [comment]
MIT license, but please put a link to https://wordpress.org/plugins/crelly-slider/ where the user can see it (in the credit sections of your project).

**Comment by fabiorino** [comment]
I have added the license file to the repo.
