### ISSUE TITLE
No lnguage files

### ISSUE THREAD

**Issue by huseyinkozan** [fabiorino/crelly-slider#7]
Can you add language files ? There are some string is not translated in Turkish.

**Comment by eduardoarandah** [comment]
I added language files for spanish. 

To create turkish translation:
-Go to languages folder
-Copy spanish .po file  and rename it with "tr_TR" at the end
-Use poedit to edit and save
-Poedit will create .mo file 
-Now it should work

To contribute via github:
-install tortoisegit (easiest way)
-in github.com fork the project
-clone in your computer
-commit changes
-push your changes
-in github.com create pull request

**Comment by huseyinkozan** [comment]
Thanks @eduardoarandah. I saw language files at the installed plugin directory. But I want to contribute translation.

**Comment by eduardoarandah** [comment]
Download poedit and make your translation

El jueves, 5 de marzo de 2015, Hüseyin Kozan <notifications@github.com>
escribió:

> Thanks @eduardoarandah <https://github.com/eduardoarandah>. I saw
> language files at the installed plugin directory. But I want to contribute
> translation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabiorino/crelly-slider/issues/7#issuecomment-77414108>
> .
>


-- 
Enviado desde mi móvil
