### ISSUE TITLE
event.mouseHooks is broken in jquery 3 

### ISSUE THREAD

**Issue by web86** [fabiorino/crelly-slider#74]
Hi, I like your plugin, but since wp3.5.6 slider doesnt work, there is Uncaught TypeError: Cannot read property 'concat' of undefined.
seems like event.mouseHooks is broken in jquery 3.5

**Comment by daveit** [comment]
Are you sure you mean WP3.5.6 ?
That is very old!

**Comment by web86** [comment]
Oh, thats true, I mean about  version 5.6 ))

**Comment by fabiorino** [comment]
Hi, I'm working on a fix.

**Comment by fabiorino** [comment]
Fixed in 1.4.4

**Comment by daveit** [comment]
Thanks Fabio, appreciate the prompt action and support - have a great weekend..
Dave-P
