### ISSUE TITLE
slides not visible

### ISSUE THREAD

**Issue by ajayphp** [fabiorino/crelly-slider#8]
Hi, 

i created slider and add two slides
aand then put the short code in post 
slider show the loading icon but nothing background as color selected
and nothing text. 

so how to display that slider

-- go it resolved .. as some theme using jquery 1.7 and i hope it needed more later version 
what min jquery version this is working.

**Comment by ajayphp** [comment]
i also saw error: Uncaught TypeError: undefined is not a function  in jquery.crellyslider.min.js?ver=0.8.2:11

and then dispay:none of slide and that displau:none should be display:block upon active slide
but all hide and not any animation work of text overlay etc.

why not create video how to all.

**Comment by fabiorino** [comment]
Ok perfect!
