### ISSUE TITLE
Specify class to add to text or image elements

### ISSUE THREAD

**Issue by schlessera** [fabiorino/crelly-slider#9]
Hi,

I looked everywhere but could not find a way to add one or more classes to text or image elements. This would be very convenient to be able to style the different elements through the normal stylesheets. I would really hate to have to add lots of custom CSS to every element, where I can't use Sass or a convenient management workflow.

Is it possible to add a filed for both text and image elements where one can type one or more classes that will then get appended to the element's markup?

Thanks,
Alain Schlesser

**Comment by fabiorino** [comment]
Hi, for now it's not possible. It's a feature that I'll add in the next release
